### ISSUE TITLE
Operation timed out Issues and Many More

### ISSUE THREAD

**Issue by phpmods** [paypal/PayPal-PHP-SDK#1045]
> For internal tracking: PPPLPAYPT-32439

I keep trying to make the PayPal Api work. Below you can see the part of code that I am using (I have removed a few non important parts of the script):
`public function purchase() {
        require realpath(__DIR__ . '/../..') . '/vendors/paypal/autoload.php';

        $custom = '00001-00002';

        $apiContext = new \PayPal\Rest\ApiContext(
            new \PayPal\Auth\OAuthTokenCredential(
                'AAA',
                'BBB'
            )
        );

        $apiContext->setConfig(
            array(
                'log.LogEnabled' => true,
                'log.FileName' => 'PayPal.log',
                'log.LogLevel' => 'FINE',
                'mode' => 'sandbox',
            )
        );

        $payer = new \PayPal\Api\Payer();
        $payer->setPaymentMethod('paypal');

        $amount = new \PayPal\Api\Amount();
        $amount->setTotal(50);
        $amount->setCurrency('EUR');

        $item1 = new \PayPal\Api\Item();
        $itemList = new \PayPal\Api\ItemList();
        $item1->setName('Tickets')
            ->setCurrency('EUR')
            ->setQuantity(2)
            ->setSku($custom) // Similar to `item_number` in Classic API
            ->setPrice(25);
        $itemList->setItems(array($item1));

        $transaction = new \PayPal\Api\Transaction();
        $transaction->setAmount($amount)->setItemList($itemList)->setCustom($custom)->setDescription('Tickets Purchase');

        $redirectUrls = new \PayPal\Api\RedirectUrls();
        $redirectUrls->setReturnUrl(url('MyClass/purchase_completed'))
            ->setCancelUrl(url('MyClass/purchase_not_completed'));

        $payment = new \PayPal\Api\Payment();
        $payment->setIntent('sale')
            ->setPayer($payer)
            ->setTransactions(array($transaction))
            ->setRedirectUrls($redirectUrls);

        try {
            $payment->create($apiContext);
            header('Location: ' . $payment->getApprovalLink());
        } catch (\PayPal\Exception\PayPalConnectionException $ex) {
            // This will print the detailed information on the exception.
            //REALLY HELPFUL FOR DEBUGGING

            echo $ex->getData();
        }
    }
public function purchase_completed() {
        require realpath(__DIR__ . '/../..') . '/vendors/paypal/autoload.php';
        $apiContext = new \PayPal\Rest\ApiContext(
            new \PayPal\Auth\OAuthTokenCredential(
                'AAA',
                'BBB'
            )
        );
        $apiContext->setConfig(
            array(
                'log.LogEnabled' => true,
                'log.FileName' => 'PayPal.log',
                'log.LogLevel' => 'FINE',
                'mode' => 'sandbox',
            )
        );
        $paymentId = $_GET['paymentId'];
        $payment = \PayPal\Api\Payment::get($paymentId, $apiContext);
        $execution = new \PayPal\Api\PaymentExecution();
        $execution->setPayerId($_GET['PayerID']);

        try {
            $result = $payment->execute($execution, $apiContext);
        } catch (Exception $ex) {
            var_dump($ex);
            $data = json_decode($ex->getData());
            $this->set('error', $data->message)
            echo 'testing2';
            //return;
        }
        echo '<pre>' . var_dump($payment).'</pre>';
        $transaction = $payment->getTransactions()[0];
        $payer = $payment->getPayer()->getPayerInfo();
        $custom = explode('-', $transaction->getCustom());
        $this->show('payment_completed');

    }`

I have been trying for a lot of hours to resolve the issue but several different errors are randomly popped up. Here is an example:

> ["url":"PayPal\Exception\PayPalConnectionException":private]=> string(87) "https://api.sandbox.paypal.com/v1/payments/payment/PAY-15C61656CT8185638LJS3GII/execute" ["data":"PayPal\Exception\PayPalConnectionException":private]=> NULL ["message":protected]=> string(66) "Operation timed out after 60001 milliseconds with 0 bytes received" ["string":"Exception":private]=> string(0) ""

And here is a part of the Paypal.log:

> [22-01-2018 09:47:09] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.sandbox.paypal.com/v1/oauth2/token
[22-01-2018 09:47:12] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 200
[22-01-2018 09:47:12] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.sandbox.paypal.com/v1/payments/payment
[22-01-2018 09:47:13] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 201
[22-01-2018 09:47:25] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.sandbox.paypal.com/v1/oauth2/token
[22-01-2018 09:47:25] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 200
[22-01-2018 09:47:25] PayPal\Core\PayPalHttpConnection : INFO: GET https://api.sandbox.paypal.com/v1/payments/payment/PAY-15C61656CT8185638LJS3GII
[22-01-2018 09:47:26] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 200
[22-01-2018 09:47:26] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.sandbox.paypal.com/v1/payments/payment/PAY-15C61656CT8185638LJS3GII/execute

The purchase failed after I was redirected to the paypal confirmation page and confirmed the transaction. I tried once again but it seems that the script failed in the following step:

> [22-01-2018 09:58:17] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.sandbox.paypal.com/v1/oauth2/token

Did anyone have any issue like that in the past?

**Comment by phpmods** [comment]
I just tried it once again and everything was successful.

**Comment by xiaoleih41** [comment]
Have your issue be solved? If so, could you please close this issue?

**Comment by phpmods** [comment]
Isn't there any status page from where we can check the server status?

**Comment by phpmods** [comment]
My script was running 12 hours ago but now I keep receiving ConnectionException errors. The PayPal Status Page states that everything is operational.. https://www.paypal-status.com/product/sandbox

Are we going to have the same issues with the live environment too?

**Comment by iMultis** [comment]
Confirm this error. Simple payment functionality (from samples) was working yesterday, but today I get `Operation timed out after 60001 milliseconds with 0 bytes received` all the time. Sometime some other SSL errors as well, but never succeed this morning.

**Comment by pp-randy** [comment]
@iMultis there was an issue this morning that is now resolved.  How about now?  Also any debug_ids?

**Comment by iMultis** [comment]
@pp-randy the problem still remains. Here are ids of some payments that failed:
PAY-6FE92638XN869101WLJUGPKA
PAY-7ME399114X8210246LJUGRTI
PAY-8U451935P48330817LJUGS4Y

**Comment by xiaoleih41** [comment]
It's not fixed yet. Thank you for the samples.

**Comment by knifesk** [comment]
If I list the transactions for a subscription with PHP and the SDK I get the timeout error...

If I try to do the same request with postman I get a timeout to... narrowing the start_date and end_date for the request I get this error:
![image](https://user-images.githubusercontent.com/333676/39065349-f1d1b8a8-44a7-11e8-9d11-72cff891c52a.png)

**Comment by prakash-gangadharan** [comment]
Hi @phpmods , @iMultis  and @knifesk , is this still an issue? How about now? if yes is there any recent debug_ids you have?

**Comment by prakash-gangadharan** [comment]
Hi @phpmods, @iMultis & @knifesk , am closing this issue since I didn't hear back from you guys. If you still see this time out issues around, feel free to reopen this issue with recent paypal debug_ids. 

Thanks!
