### ISSUE TITLE
INTERNAL_SERVICE_ERROR

### ISSUE THREAD

**Issue by digitalhuman** [paypal/PayPal-PHP-SDK#707]
### Required Information

- PHP Version: 5.6
- PayPal-PHP-SDK Version: Latest
- Debug ID(s):  347a30a8862f8

### Issue Description

Create payment request

```
{
	"intent": "sale",
	"payer": {
		"payment_method": "paypal"
	},
	"transactions": [
		{
			"amount": {
				"total": "10.35",
				"currency": "USD"
			}
		}
	],
	"redirect_urls": {
		"return_url": "http://www.amazon.com",
		"cancel_url": "http://www.amazon.com"
	}
}
```

# Full request:

```
POST https://api.sandbox.paypal.com/v1/payments/payment HTTP/1.1
Host: api.sandbox.paypal.com
Connection: keep-alive
Content-Length: 283
Authorization: Bearer A101.-VERY SECRET-lTATb67OQqvjdn6BAWa8BXf-2EeDqIzrbm.-ACCESS-TOKEN-_mS
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.71 Safari/537.36
Content-Type: application/json
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8,sv;q=0.6,nl;q=0.4

{
	"intent": "sale",
	"payer": {
		"payment_method": "paypal"
	},
	"transactions": [
		{
			"amount": {
				"total": "10.35",
				"currency": "USD"
			}
		}
	],
	"redirect_urls": {
		"return_url": "http://www.amazon.com",
		"cancel_url": "http://www.amazon.com"
	}
}
```

Returns with the error:

```
{
  "name": "INTERNAL_SERVICE_ERROR",
  "message": "An internal service error has occurred",
  "information_link": "https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR",
  "debug_id": "8d05854836ccf"
}
```

**Comment by redbotHQ** [comment]
Having the same issue, log data below:

[06-11-2016 02:28:40] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.sandbox.paypal.com/v1/oauth2/token
[06-11-2016 02:28:41] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 200
[06-11-2016 02:28:41] PayPal\Core\PayPalHttpConnection : INFO: POST https://api.sandbox.paypal.com/v1/payments/payment
[06-11-2016 02:28:42] PayPal\Core\PayPalHttpConnection : INFO: Response Status 	: 500
[06-11-2016 02:28:42] PayPal\Core\PayPalHttpConnection : ERROR: Got Http response code 500 when accessing https://api.sandbox.paypal.com/v1/payments/payment. {"name":"INTERNAL_SERVICE_ERROR","message":"An internal service error has occurred","information_link":"https://developer.paypal.com/docs/api/#INTERNAL_SERVICE_ERROR","debug_id":"914ea010b5bf9"}

**Comment by digitalhuman** [comment]
@redbotHQ Really annoying. I switched to Live to be able to continue working. I guess the Sadbox has issues at this moment.

**Comment by redbotHQ** [comment]
Absolutely, the issue seems to be with sandbox not code. Finger tapping time!

**Comment by luigioctaviano** [comment]
Same here guys. Error 500. I hope it will be resolved soon.
![14996310_1504111286269295_428712505_n](https://cloud.githubusercontent.com/assets/13997214/20039851/d1e28d8c-a486-11e6-8123-2bc3d6ef8834.jpg)

**Comment by digitalhuman** [comment]
@luigioctaviano i would not bet on it. I even tries contacting them on Twitter. Dead

**Comment by luigioctaviano** [comment]
@digitalhuman Yeah. Their twitter account is inactive. Is it okay already? Didn't check yet. It's now morning here in my country. I guess they will fix it when Monday strikes in US. *Hopefully*

**Comment by luigioctaviano** [comment]
@digitalhuman **Update:** It seems to be **working right now**. I hope it will not happen again. Thanks for reporting it.
![screenshot 103](https://cloud.githubusercontent.com/assets/13997214/20043502/78d90958-a4c9-11e6-8d1f-c821f41a315e.png)

**Comment by pp-randy** [comment]
I apologize for any impact the intermittent 500 errors have caused to your testing in sandbox.  We are still having intermittent issue that we are working to resolve.  I will update the thread when I have more information.

**Comment by pp-randy** [comment]
Internal Tracking: PPPLPAYPT-14452

**Comment by digitalhuman** [comment]
I am so happy that I did not waited for a solution ;)

**Comment by pp-randy** [comment]
All,
We should be good from this point.  Please let me know if you encounter further issues. 

@digitalhuman I'm sorry that the sandbox had this issue, I'm glad you were able to use live in this case.

**Comment by digitalhuman** [comment]
Hi @pp-randy, thanks. Yeah It was not a great solution to use Live because of all the 'test' transactions but I got my code finished so thats good.

**Comment by vsanjeevagowda-s** [comment]
I am getting 
PayPal::SDK::Core::Exceptions::ServerError: Failed.  Response code = 500.  Response message = Internal Server Error.  Response debug ID = 158bf207a609, 158bf207a609.

**Comment by vsanjeevagowda-s** [comment]
I am using Ruby gem respectively
paypal-sdk-adaptiveaccounts (1.102.1)
      paypal-sdk-core (~> 0.3.0)
    paypal-sdk-core (0.3.4)
      multi_json (~> 1.0)
      xml-simple
    paypal-sdk-rest (1.6.0)

**Comment by papipons** [comment]
Good day, I am encountering this issue today. Earlier in the morning, I had INTERNAL SERVICE ERRORS on payment creation, for some reason it worked after lunch time, but now I am having same errors in payment execution. Debug ID: 2d0ece9526806

**Comment by xiaoleih41** [comment]
The issue should have been solved. Please test again.

**Comment by lookingup77** [comment]
Hello, i am also still having the issue today on payment creation.
![screenshot from 2017-08-31 11-13-20](https://user-images.githubusercontent.com/31505022/29915907-7da8f43a-8e3d-11e7-95b1-eddd5fa17849.png)

**Comment by xiaoleih41** [comment]
@lookingup77 500 internal server error can be caused by different issues. Please open a new ticket with your`debugId` for us to do research. I am locking this issue conversation as the original issue has been solved.
